version: '3.7'
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    restart: always
    container_name: dynamodb
    ports:
      - 8000:8000
    networks:
      - stack
    volumes:
      - dynamodb-data:/data
    entrypoint: "java"
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]
networks:
  stack:
    driver: bridge
volumes:
  dynamodb-data: